### ISSUE TITLE
camb_clfile with _lensPotentialCls.dat files

### ISSUE THREAD

**Issue by cmbant** [JulienPeloton/lenscov#1]
Seems to not handle CAMB output lensPotentialCls.dat files (and no error checking on number of columns).

This is the preferred format for unlensed spectra, _scalCls is just for historical compatibility. Avoids messy dependence on T_CMB, different L^4 factors, etc, as well as having E-phi correlations.

Note that CAMB outputs may or may not have header comment row explicitly giving column content (introduced in recent version).

**Comment by JulienPeloton** [comment]
OK, lib_spectra can now handle _lensPotentialCls in addition to _scalCls.
Thanks!

**Comment by cmbant** [comment]
Great! But the factors in the lenspotentialCls file should be (l(l+1)]^2/2pi for pp etc, looks off (and not sure why tcmb is now 1 in the case of scalcls?).  Did you check result for consistency between what you get from scalCls and lenspotentialCls?

**Comment by JulienPeloton** [comment]
OK, should be fixed (ell normalisation, 2pi factor, tcmb factor).
From a simple check, it seems that the code outputs the same answer no matter scalCls or lenspotentialCls.
Let me know if you still encounter problem :-)

**Comment by cmbant** [comment]
I think the scalCls were correct originally (l^4 factors, not [l(l+1)]^2). I still get differences

```
   cls_unlensed = lib_spectra.get_camb_cls(fname='/vagrant/notebooks/inputs/base_plikHM_TT_lowTEB_lensing_scalCls.dat',lmax=lmax)
   cls_unlensed2 = lib_spectra.get_camb_cls(fname='/vagrant/notebooks/inputs/base_plikHM_TT_lowTEB_lensing_lenspotentialCls.dat',lmax=lmax)
   print cls_unlensed.clpp[2:]/cls_unlensed2.clpp[2:]-1
```

**Comment by JulienPeloton** [comment]
OK. Changing the normalisation to ell**4 for scalCls, and (ell*(ell+1))**2 for lenspotentialCls gives me 1e-5 relative difference per mode up to ell_max = 3000 (1e-7 for the mean).
I would say this is OK, although not perfect.

Why there is such difference in the normalisation between files?
![diff_clpp](https://cloud.githubusercontent.com/assets/20426972/21359920/1fd39a44-c6de-11e6-9ab4-ab825e4e3d85.png)

**Comment by cmbant** [comment]
Looks fine. scalCls is the legacy format, more consistent with CMBfast. That's why I introduced the more sensibly normalized lenspotentialCls file at some point.

**Comment by JulienPeloton** [comment]
I see. 
Thanks for the catch!
