### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by cmbant** [JulienPeloton/lenscov#2]
pycharm immediately spots quite a few problems with unused variables, e.g. in covarainces.py, cov_order0_tot is unused if file_manager.FileExists is true (i.e. array_to_save has wrong indent) - likewise for other modes.

**Comment by JulienPeloton** [comment]
OK. It used to be useful at some point (to load data instead of re-computing) but isn't anymore.
covariance.py exits itself now if data you want to compute are already stored on the disk.
