### ISSUE TITLE
matplotlib and plot settings

### ISSUE THREAD

**Issue by cmbant** [JulienPeloton/lenscov#3]
Perhaps remove the matplotlib config code that's always called, e.g. in lib_spectra?

Doing
  %matplotlib inline
  import lib_covariances,lib_spectra
  from correlation_functions import correlation_functions

gives the Agg usage warning, and then subsequent ipython notebook plots don't appear.

**Comment by JulienPeloton** [comment]
Thanks for noticing it! 
I just removed all stuff related to matplotlib as it is not required in this version of the package (no plots done internally). That should work.

**Comment by cmbant** [comment]
Thanks, seems fixed!
